config/routes.rb
MedicalMarijuanaDelivery::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "landings/index"
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root :to => 'products#index'
  match '/product_info', to: 'landings#product_info',  via: 'get'

  resources :products

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      post 'signup',      :to => 'registrations#create'
      put 'user',         :to => 'registrations#update'
      get 'user',         :to => 'registrations#show'
      post 'login',       :to => 'sessions#create'
      delete 'signout',   :to => 'sessions#destroy'
      get 'users/status', :to => 'sessions#status'
      resources :orders
      resources :products
      resources :product_options
      resources :order_items
      resources :preferences
    end
  end


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  #->Prelang (user_login:devise/stylized_paths)
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
    @products = Product.all 
  end


end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/views/landings/_product_info.html.haml
- @products.each do |product|
  %h1
    = link_to product.name, product_info_url
  %br/
  %p.text-info
    = product.description
  %br/
  .pictures
    - product.pictures.each do |picture|
      .single-item
        = image_tag picture.product_image.url(:medium)
  %br/

app/views/landings/index.html.haml
.container
  .row
    .col-md-4
      - if signed_in?
        = render 'product_info'
      - else
        .container.margin-top-10em
          .buttons
            = link_to 'Sign In', new_user_session_url, class:"btn btn-primary btn-lg btn-block"
            %br/
          .buttons
            = link_to 'Sign Up', new_user_registration_url, class:"btn btn-primary btn-lg btn-block"

app/views/landings/product_info.html.haml
    /  = image_tag product.picture